[2020-04-07 16:04:19,076] {scheduler_job.py:153} INFO - Started process (PID=63373) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:04:19,082] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 16:04:19,083] {logging_mixin.py:112} INFO - [2020-04-07 16:04:19,083] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:04:19,558] {logging_mixin.py:112} INFO - [2020-04-07 16:04:19,557] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 16:04:19,559] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:04:19,565] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.489 seconds
[2020-04-07 16:05:29,293] {scheduler_job.py:153} INFO - Started process (PID=63412) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:05:29,299] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 16:05:29,300] {logging_mixin.py:112} INFO - [2020-04-07 16:05:29,300] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:05:29,626] {logging_mixin.py:112} INFO - [2020-04-07 16:05:29,624] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 16:05:29,627] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:05:29,633] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.340 seconds
[2020-04-07 16:06:39,518] {scheduler_job.py:153} INFO - Started process (PID=63451) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:06:39,523] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 16:06:39,524] {logging_mixin.py:112} INFO - [2020-04-07 16:06:39,524] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:06:39,778] {logging_mixin.py:112} INFO - [2020-04-07 16:06:39,777] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 16:06:39,779] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:06:39,791] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.274 seconds
[2020-04-07 16:07:49,718] {scheduler_job.py:153} INFO - Started process (PID=63489) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:07:49,724] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 16:07:49,725] {logging_mixin.py:112} INFO - [2020-04-07 16:07:49,724] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:07:50,018] {logging_mixin.py:112} INFO - [2020-04-07 16:07:50,017] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 16:07:50,019] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:07:50,027] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.309 seconds
[2020-04-07 16:08:59,915] {scheduler_job.py:153} INFO - Started process (PID=63530) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:08:59,921] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 16:08:59,922] {logging_mixin.py:112} INFO - [2020-04-07 16:08:59,921] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:09:00,101] {logging_mixin.py:112} INFO - [2020-04-07 16:09:00,100] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 16:09:00,101] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:09:00,116] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.201 seconds
[2020-04-07 16:10:10,131] {scheduler_job.py:153} INFO - Started process (PID=63568) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:10:10,137] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 16:10:10,138] {logging_mixin.py:112} INFO - [2020-04-07 16:10:10,137] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:10:10,385] {logging_mixin.py:112} INFO - [2020-04-07 16:10:10,384] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 16:10:10,385] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:10:10,394] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.263 seconds
[2020-04-07 16:11:20,317] {scheduler_job.py:153} INFO - Started process (PID=63612) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:11:20,332] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 16:11:20,333] {logging_mixin.py:112} INFO - [2020-04-07 16:11:20,332] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:11:20,560] {logging_mixin.py:112} INFO - [2020-04-07 16:11:20,559] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 16:11:20,560] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:11:20,570] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.252 seconds
[2020-04-07 16:12:30,520] {scheduler_job.py:153} INFO - Started process (PID=63654) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:12:30,526] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 16:12:30,527] {logging_mixin.py:112} INFO - [2020-04-07 16:12:30,527] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:12:30,714] {logging_mixin.py:112} INFO - [2020-04-07 16:12:30,713] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 16:12:30,715] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:12:30,729] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.208 seconds
[2020-04-07 16:13:40,726] {scheduler_job.py:153} INFO - Started process (PID=63695) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:13:40,732] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 16:13:40,733] {logging_mixin.py:112} INFO - [2020-04-07 16:13:40,733] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:13:40,961] {logging_mixin.py:112} INFO - [2020-04-07 16:13:40,960] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 16:13:40,962] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:13:40,969] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.243 seconds
[2020-04-07 16:14:50,911] {scheduler_job.py:153} INFO - Started process (PID=63733) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:14:50,917] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 16:14:50,917] {logging_mixin.py:112} INFO - [2020-04-07 16:14:50,917] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:14:51,105] {logging_mixin.py:112} INFO - [2020-04-07 16:14:51,104] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 16:14:51,106] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:14:51,120] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.209 seconds
[2020-04-07 16:16:01,119] {scheduler_job.py:153} INFO - Started process (PID=63772) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:16:01,125] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 16:16:01,126] {logging_mixin.py:112} INFO - [2020-04-07 16:16:01,126] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:16:01,322] {logging_mixin.py:112} INFO - [2020-04-07 16:16:01,321] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 16:16:01,322] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:16:01,332] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.213 seconds
[2020-04-07 16:17:11,322] {scheduler_job.py:153} INFO - Started process (PID=63810) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:17:11,327] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 16:17:11,328] {logging_mixin.py:112} INFO - [2020-04-07 16:17:11,328] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:17:11,522] {logging_mixin.py:112} INFO - [2020-04-07 16:17:11,521] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 16:17:11,523] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:17:11,536] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.214 seconds
[2020-04-07 16:18:21,515] {scheduler_job.py:153} INFO - Started process (PID=63849) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:18:21,521] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 16:18:21,522] {logging_mixin.py:112} INFO - [2020-04-07 16:18:21,522] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:18:21,710] {logging_mixin.py:112} INFO - [2020-04-07 16:18:21,709] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 16:18:21,710] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:18:21,724] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.209 seconds
[2020-04-07 16:19:31,726] {scheduler_job.py:153} INFO - Started process (PID=63888) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:19:31,732] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 16:19:31,733] {logging_mixin.py:112} INFO - [2020-04-07 16:19:31,732] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:19:31,927] {logging_mixin.py:112} INFO - [2020-04-07 16:19:31,926] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 16:19:31,927] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:19:31,941] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.216 seconds
[2020-04-07 16:20:46,220] {scheduler_job.py:153} INFO - Started process (PID=63962) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:20:46,229] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 16:20:46,230] {logging_mixin.py:112} INFO - [2020-04-07 16:20:46,229] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:20:46,487] {logging_mixin.py:112} INFO - [2020-04-07 16:20:46,486] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 16:20:46,488] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:20:46,496] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.276 seconds
[2020-04-07 16:43:04,151] {scheduler_job.py:153} INFO - Started process (PID=64095) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:43:04,158] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 16:43:04,159] {logging_mixin.py:112} INFO - [2020-04-07 16:43:04,158] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:43:04,384] {logging_mixin.py:112} INFO - [2020-04-07 16:43:04,383] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 16:43:04,384] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:43:04,417] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.267 seconds
[2020-04-07 16:43:28,101] {scheduler_job.py:153} INFO - Started process (PID=64132) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:43:28,108] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 16:43:28,109] {logging_mixin.py:112} INFO - [2020-04-07 16:43:28,109] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:43:28,319] {logging_mixin.py:112} INFO - [2020-04-07 16:43:28,318] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 16:43:28,319] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:43:28,328] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.227 seconds
[2020-04-07 16:44:28,320] {scheduler_job.py:153} INFO - Started process (PID=64178) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:44:28,327] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 16:44:28,328] {logging_mixin.py:112} INFO - [2020-04-07 16:44:28,327] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:44:28,522] {logging_mixin.py:112} INFO - [2020-04-07 16:44:28,520] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 16:44:28,522] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:44:28,531] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.212 seconds
[2020-04-07 16:47:14,701] {scheduler_job.py:153} INFO - Started process (PID=64226) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:47:19,726] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 16:47:19,729] {logging_mixin.py:112} INFO - [2020-04-07 16:47:19,728] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:47:20,300] {logging_mixin.py:112} INFO - [2020-04-07 16:47:20,298] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 16:47:20,300] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 16:47:20,320] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 5.620 seconds
[2020-04-07 17:25:12,101] {scheduler_job.py:153} INFO - Started process (PID=64281) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:25:12,107] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 17:25:12,108] {logging_mixin.py:112} INFO - [2020-04-07 17:25:12,108] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:25:12,293] {logging_mixin.py:112} INFO - [2020-04-07 17:25:12,292] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:25:12,293] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:25:12,302] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.201 seconds
[2020-04-07 17:26:22,438] {scheduler_job.py:153} INFO - Started process (PID=64322) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:26:22,444] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 17:26:22,445] {logging_mixin.py:112} INFO - [2020-04-07 17:26:22,444] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:26:22,615] {logging_mixin.py:112} INFO - [2020-04-07 17:26:22,614] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:26:22,615] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:26:22,629] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.191 seconds
[2020-04-07 17:27:45,085] {scheduler_job.py:153} INFO - Started process (PID=64368) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:27:45,091] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 17:27:45,092] {logging_mixin.py:112} INFO - [2020-04-07 17:27:45,092] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:27:45,324] {logging_mixin.py:112} INFO - [2020-04-07 17:27:45,323] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:27:45,325] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:27:45,333] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.248 seconds
[2020-04-07 17:33:34,211] {scheduler_job.py:153} INFO - Started process (PID=64437) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:33:34,217] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 17:33:34,219] {logging_mixin.py:112} INFO - [2020-04-07 17:33:34,218] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:33:34,436] {logging_mixin.py:112} INFO - [2020-04-07 17:33:34,435] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:33:34,437] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:33:34,445] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.234 seconds
[2020-04-07 17:34:14,272] {scheduler_job.py:153} INFO - Started process (PID=64482) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:34:14,279] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 17:34:14,280] {logging_mixin.py:112} INFO - [2020-04-07 17:34:14,280] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:34:14,474] {logging_mixin.py:112} INFO - [2020-04-07 17:34:14,473] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:34:14,474] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:34:14,484] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.211 seconds
[2020-04-07 17:35:24,698] {scheduler_job.py:153} INFO - Started process (PID=64521) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:35:24,704] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 17:35:24,704] {logging_mixin.py:112} INFO - [2020-04-07 17:35:24,704] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:35:24,877] {logging_mixin.py:112} INFO - [2020-04-07 17:35:24,876] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:35:24,878] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:35:24,889] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.191 seconds
[2020-04-07 17:36:54,783] {scheduler_job.py:153} INFO - Started process (PID=64574) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:36:54,789] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 17:36:54,789] {logging_mixin.py:112} INFO - [2020-04-07 17:36:54,789] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:36:54,988] {logging_mixin.py:112} INFO - [2020-04-07 17:36:54,987] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:36:54,988] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:36:54,998] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.215 seconds
[2020-04-07 17:37:46,890] {scheduler_job.py:153} INFO - Started process (PID=64625) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:37:46,896] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 17:37:46,897] {logging_mixin.py:112} INFO - [2020-04-07 17:37:46,897] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:37:47,143] {logging_mixin.py:112} INFO - [2020-04-07 17:37:47,141] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:37:47,143] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:37:47,151] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.261 seconds
[2020-04-07 17:38:57,038] {scheduler_job.py:153} INFO - Started process (PID=64667) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:38:57,046] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 17:38:57,048] {logging_mixin.py:112} INFO - [2020-04-07 17:38:57,047] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:38:57,417] {logging_mixin.py:112} INFO - [2020-04-07 17:38:57,416] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:38:57,418] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:38:57,428] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.390 seconds
[2020-04-07 17:40:07,217] {scheduler_job.py:153} INFO - Started process (PID=64710) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:40:07,224] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 17:40:07,225] {logging_mixin.py:112} INFO - [2020-04-07 17:40:07,225] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:40:07,629] {logging_mixin.py:112} INFO - [2020-04-07 17:40:07,628] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:40:07,630] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:40:07,641] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.424 seconds
[2020-04-07 17:41:17,432] {scheduler_job.py:153} INFO - Started process (PID=64756) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:41:17,439] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 17:41:17,440] {logging_mixin.py:112} INFO - [2020-04-07 17:41:17,439] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:41:17,612] {logging_mixin.py:112} INFO - [2020-04-07 17:41:17,611] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:41:17,612] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:41:17,626] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.194 seconds
[2020-04-07 17:42:27,623] {scheduler_job.py:153} INFO - Started process (PID=64795) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:42:27,629] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 17:42:27,630] {logging_mixin.py:112} INFO - [2020-04-07 17:42:27,629] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:42:27,803] {logging_mixin.py:112} INFO - [2020-04-07 17:42:27,803] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:42:27,804] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:42:27,819] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.196 seconds
[2020-04-07 17:43:37,824] {scheduler_job.py:153} INFO - Started process (PID=64833) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:43:37,831] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 17:43:37,832] {logging_mixin.py:112} INFO - [2020-04-07 17:43:37,831] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:43:38,035] {logging_mixin.py:112} INFO - [2020-04-07 17:43:38,033] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:43:38,035] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:43:38,044] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.220 seconds
[2020-04-07 17:44:48,031] {scheduler_job.py:153} INFO - Started process (PID=64883) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:44:48,039] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 17:44:48,040] {logging_mixin.py:112} INFO - [2020-04-07 17:44:48,039] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:44:48,417] {logging_mixin.py:112} INFO - [2020-04-07 17:44:48,415] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:44:48,417] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:44:48,430] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.399 seconds
[2020-04-07 17:45:58,222] {scheduler_job.py:153} INFO - Started process (PID=64925) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:45:58,230] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 17:45:58,231] {logging_mixin.py:112} INFO - [2020-04-07 17:45:58,230] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:45:58,518] {logging_mixin.py:112} INFO - [2020-04-07 17:45:58,517] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:45:58,519] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:45:58,528] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.306 seconds
[2020-04-07 17:47:08,382] {scheduler_job.py:153} INFO - Started process (PID=64964) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:47:08,394] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 17:47:08,396] {logging_mixin.py:112} INFO - [2020-04-07 17:47:08,395] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:47:08,569] {logging_mixin.py:112} INFO - [2020-04-07 17:47:08,568] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:47:08,570] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:47:08,583] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.202 seconds
[2020-04-07 17:48:18,604] {scheduler_job.py:153} INFO - Started process (PID=65003) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:48:18,612] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 17:48:18,613] {logging_mixin.py:112} INFO - [2020-04-07 17:48:18,613] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:48:18,825] {logging_mixin.py:112} INFO - [2020-04-07 17:48:18,824] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:48:18,826] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:48:18,835] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.232 seconds
[2020-04-07 17:49:28,784] {scheduler_job.py:153} INFO - Started process (PID=65041) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:49:28,791] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 17:49:28,793] {logging_mixin.py:112} INFO - [2020-04-07 17:49:28,792] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:49:28,965] {logging_mixin.py:112} INFO - [2020-04-07 17:49:28,964] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:49:28,965] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:49:28,973] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.190 seconds
[2020-04-07 17:50:38,998] {scheduler_job.py:153} INFO - Started process (PID=65079) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:50:39,004] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 17:50:39,005] {logging_mixin.py:112} INFO - [2020-04-07 17:50:39,005] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:50:39,210] {logging_mixin.py:112} INFO - [2020-04-07 17:50:39,209] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:50:39,211] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:50:39,219] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.221 seconds
[2020-04-07 17:51:49,345] {scheduler_job.py:153} INFO - Started process (PID=65127) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:51:49,353] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 17:51:49,354] {logging_mixin.py:112} INFO - [2020-04-07 17:51:49,354] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:51:49,560] {logging_mixin.py:112} INFO - [2020-04-07 17:51:49,559] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:51:49,560] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:51:49,568] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.223 seconds
[2020-04-07 17:52:59,648] {scheduler_job.py:153} INFO - Started process (PID=65165) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:52:59,655] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 17:52:59,657] {logging_mixin.py:112} INFO - [2020-04-07 17:52:59,656] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:52:59,850] {logging_mixin.py:112} INFO - [2020-04-07 17:52:59,848] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:52:59,850] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:52:59,920] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.272 seconds
[2020-04-07 17:54:09,951] {scheduler_job.py:153} INFO - Started process (PID=65205) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:54:09,957] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 17:54:09,958] {logging_mixin.py:112} INFO - [2020-04-07 17:54:09,958] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:54:10,214] {logging_mixin.py:112} INFO - [2020-04-07 17:54:10,213] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:54:10,214] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:54:10,223] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.272 seconds
[2020-04-07 17:55:20,363] {scheduler_job.py:153} INFO - Started process (PID=65245) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:55:20,377] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 17:55:20,378] {logging_mixin.py:112} INFO - [2020-04-07 17:55:20,377] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:55:20,613] {logging_mixin.py:112} INFO - [2020-04-07 17:55:20,612] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:55:20,614] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:55:20,625] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.262 seconds
[2020-04-07 17:56:30,641] {scheduler_job.py:153} INFO - Started process (PID=65293) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:56:30,647] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 17:56:30,648] {logging_mixin.py:112} INFO - [2020-04-07 17:56:30,648] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:56:30,886] {logging_mixin.py:112} INFO - [2020-04-07 17:56:30,885] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:56:30,886] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:56:30,898] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.257 seconds
[2020-04-07 17:57:40,858] {scheduler_job.py:153} INFO - Started process (PID=65331) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:57:40,864] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 17:57:40,864] {logging_mixin.py:112} INFO - [2020-04-07 17:57:40,864] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:57:41,099] {logging_mixin.py:112} INFO - [2020-04-07 17:57:41,098] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:57:41,099] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:57:41,111] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.254 seconds
[2020-04-07 17:58:51,071] {scheduler_job.py:153} INFO - Started process (PID=65370) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:58:51,077] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 17:58:51,078] {logging_mixin.py:112} INFO - [2020-04-07 17:58:51,077] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:58:51,311] {logging_mixin.py:112} INFO - [2020-04-07 17:58:51,310] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:58:51,312] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 17:58:51,324] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.253 seconds
[2020-04-07 18:00:01,288] {scheduler_job.py:153} INFO - Started process (PID=65408) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:00:01,294] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 18:00:01,295] {logging_mixin.py:112} INFO - [2020-04-07 18:00:01,294] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:00:01,546] {logging_mixin.py:112} INFO - [2020-04-07 18:00:01,545] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 18:00:01,546] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:00:01,554] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.266 seconds
[2020-04-07 18:01:11,545] {scheduler_job.py:153} INFO - Started process (PID=65457) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:01:11,550] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 18:01:11,551] {logging_mixin.py:112} INFO - [2020-04-07 18:01:11,551] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:01:11,797] {logging_mixin.py:112} INFO - [2020-04-07 18:01:11,796] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 18:01:11,797] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:01:11,803] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.259 seconds
[2020-04-07 18:02:21,899] {scheduler_job.py:153} INFO - Started process (PID=65496) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:02:21,906] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 18:02:21,907] {logging_mixin.py:112} INFO - [2020-04-07 18:02:21,907] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:02:22,170] {logging_mixin.py:112} INFO - [2020-04-07 18:02:22,169] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 18:02:22,170] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:02:22,176] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.277 seconds
[2020-04-07 18:03:32,256] {scheduler_job.py:153} INFO - Started process (PID=65534) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:03:32,265] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 18:03:32,267] {logging_mixin.py:112} INFO - [2020-04-07 18:03:32,266] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:03:32,539] {logging_mixin.py:112} INFO - [2020-04-07 18:03:32,538] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 18:03:32,540] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:03:32,551] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.295 seconds
[2020-04-07 18:04:42,642] {scheduler_job.py:153} INFO - Started process (PID=65573) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:04:42,648] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 18:04:42,649] {logging_mixin.py:112} INFO - [2020-04-07 18:04:42,649] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:04:42,885] {logging_mixin.py:112} INFO - [2020-04-07 18:04:42,884] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 18:04:42,885] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:04:42,897] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.255 seconds
[2020-04-07 18:05:53,049] {scheduler_job.py:153} INFO - Started process (PID=65613) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:05:53,055] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 18:05:53,056] {logging_mixin.py:112} INFO - [2020-04-07 18:05:53,055] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:05:53,296] {logging_mixin.py:112} INFO - [2020-04-07 18:05:53,295] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 18:05:53,296] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:05:53,309] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.260 seconds
[2020-04-07 18:38:53,051] {scheduler_job.py:153} INFO - Started process (PID=65692) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:38:53,057] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 18:38:53,058] {logging_mixin.py:112} INFO - [2020-04-07 18:38:53,057] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:38:53,328] {logging_mixin.py:112} INFO - [2020-04-07 18:38:53,327] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 18:38:53,328] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:38:53,336] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.285 seconds
[2020-04-07 18:40:03,240] {scheduler_job.py:153} INFO - Started process (PID=65739) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:40:03,246] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 18:40:03,247] {logging_mixin.py:112} INFO - [2020-04-07 18:40:03,247] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:40:03,515] {logging_mixin.py:112} INFO - [2020-04-07 18:40:03,514] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 18:40:03,515] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:40:03,521] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.282 seconds
[2020-04-07 18:41:13,412] {scheduler_job.py:153} INFO - Started process (PID=65778) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:41:13,418] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 18:41:13,419] {logging_mixin.py:112} INFO - [2020-04-07 18:41:13,419] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:41:13,674] {logging_mixin.py:112} INFO - [2020-04-07 18:41:13,673] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 18:41:13,674] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:41:13,681] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.270 seconds
[2020-04-07 18:42:23,622] {scheduler_job.py:153} INFO - Started process (PID=65817) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:42:23,632] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 18:42:23,633] {logging_mixin.py:112} INFO - [2020-04-07 18:42:23,633] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:42:23,893] {logging_mixin.py:112} INFO - [2020-04-07 18:42:23,892] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 18:42:23,894] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:42:23,900] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.279 seconds
[2020-04-07 18:43:45,378] {scheduler_job.py:153} INFO - Started process (PID=65864) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:43:45,385] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 18:43:45,386] {logging_mixin.py:112} INFO - [2020-04-07 18:43:45,385] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:43:45,647] {logging_mixin.py:112} INFO - [2020-04-07 18:43:45,646] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 18:43:45,647] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:43:45,671] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.293 seconds
[2020-04-07 18:45:17,314] {scheduler_job.py:153} INFO - Started process (PID=65916) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:45:17,321] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 18:45:17,322] {logging_mixin.py:112} INFO - [2020-04-07 18:45:17,322] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:45:17,495] {logging_mixin.py:112} INFO - [2020-04-07 18:45:17,494] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 18:45:17,495] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:45:17,509] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.195 seconds
[2020-04-07 18:46:37,870] {scheduler_job.py:153} INFO - Started process (PID=67582) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:46:37,877] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 18:46:37,878] {logging_mixin.py:112} INFO - [2020-04-07 18:46:37,878] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:46:38,238] {logging_mixin.py:112} INFO - [2020-04-07 18:46:38,237] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 18:46:38,238] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:46:38,247] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.378 seconds
[2020-04-07 18:47:48,203] {scheduler_job.py:153} INFO - Started process (PID=67650) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:47:48,210] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 18:47:48,211] {logging_mixin.py:112} INFO - [2020-04-07 18:47:48,210] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:47:48,391] {logging_mixin.py:112} INFO - [2020-04-07 18:47:48,390] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 18:47:48,392] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:47:48,400] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.197 seconds
[2020-04-07 18:48:58,524] {scheduler_job.py:153} INFO - Started process (PID=67688) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:48:58,532] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 18:48:58,533] {logging_mixin.py:112} INFO - [2020-04-07 18:48:58,533] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:48:58,729] {logging_mixin.py:112} INFO - [2020-04-07 18:48:58,728] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 18:48:58,729] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:48:58,738] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.214 seconds
[2020-04-07 18:50:08,870] {scheduler_job.py:153} INFO - Started process (PID=67728) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:50:08,876] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 18:50:08,877] {logging_mixin.py:112} INFO - [2020-04-07 18:50:08,877] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:50:09,048] {logging_mixin.py:112} INFO - [2020-04-07 18:50:09,047] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 18:50:09,049] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:50:09,063] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.193 seconds
[2020-04-07 18:51:30,634] {scheduler_job.py:153} INFO - Started process (PID=67771) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:51:30,640] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 18:51:30,641] {logging_mixin.py:112} INFO - [2020-04-07 18:51:30,640] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:51:30,811] {logging_mixin.py:112} INFO - [2020-04-07 18:51:30,810] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 18:51:30,812] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:51:30,820] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.186 seconds
[2020-04-07 18:52:51,413] {scheduler_job.py:153} INFO - Started process (PID=67817) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:52:51,419] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 18:52:51,421] {logging_mixin.py:112} INFO - [2020-04-07 18:52:51,420] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:52:51,615] {logging_mixin.py:112} INFO - [2020-04-07 18:52:51,614] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 18:52:51,616] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 18:52:51,626] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.214 seconds
[2020-04-07 19:26:51,193] {scheduler_job.py:153} INFO - Started process (PID=67878) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:26:51,207] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 19:26:51,209] {logging_mixin.py:112} INFO - [2020-04-07 19:26:51,208] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:26:51,383] {logging_mixin.py:112} INFO - [2020-04-07 19:26:51,382] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:26:51,383] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:26:51,397] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.203 seconds
[2020-04-07 19:28:01,407] {scheduler_job.py:153} INFO - Started process (PID=67919) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:28:01,412] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 19:28:01,413] {logging_mixin.py:112} INFO - [2020-04-07 19:28:01,413] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:28:01,596] {logging_mixin.py:112} INFO - [2020-04-07 19:28:01,595] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:28:01,596] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:28:01,606] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.199 seconds
[2020-04-07 19:29:11,609] {scheduler_job.py:153} INFO - Started process (PID=67972) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:29:11,616] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 19:29:11,617] {logging_mixin.py:112} INFO - [2020-04-07 19:29:11,616] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:29:11,980] {logging_mixin.py:112} INFO - [2020-04-07 19:29:11,979] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:29:11,981] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:29:11,989] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.380 seconds
[2020-04-07 19:30:21,789] {scheduler_job.py:153} INFO - Started process (PID=68014) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:30:21,801] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 19:30:21,802] {logging_mixin.py:112} INFO - [2020-04-07 19:30:21,802] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:30:22,025] {logging_mixin.py:112} INFO - [2020-04-07 19:30:22,023] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:30:22,025] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:30:22,034] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.245 seconds
[2020-04-07 19:31:31,983] {scheduler_job.py:153} INFO - Started process (PID=68053) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:31:31,989] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 19:31:31,990] {logging_mixin.py:112} INFO - [2020-04-07 19:31:31,990] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:31:32,164] {logging_mixin.py:112} INFO - [2020-04-07 19:31:32,162] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:31:32,164] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:31:32,178] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.195 seconds
[2020-04-07 19:32:42,194] {scheduler_job.py:153} INFO - Started process (PID=68091) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:32:42,202] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 19:32:42,204] {logging_mixin.py:112} INFO - [2020-04-07 19:32:42,203] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:32:42,383] {logging_mixin.py:112} INFO - [2020-04-07 19:32:42,382] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:32:42,383] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:32:42,397] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.203 seconds
[2020-04-07 19:33:52,408] {scheduler_job.py:153} INFO - Started process (PID=68131) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:33:52,414] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 19:33:52,415] {logging_mixin.py:112} INFO - [2020-04-07 19:33:52,414] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:33:52,589] {logging_mixin.py:112} INFO - [2020-04-07 19:33:52,588] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:33:52,589] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:33:52,603] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.194 seconds
[2020-04-07 19:35:02,603] {scheduler_job.py:153} INFO - Started process (PID=68170) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:35:02,609] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 19:35:02,610] {logging_mixin.py:112} INFO - [2020-04-07 19:35:02,610] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:35:02,781] {logging_mixin.py:112} INFO - [2020-04-07 19:35:02,780] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:35:02,782] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:35:02,796] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.192 seconds
[2020-04-07 19:36:12,875] {scheduler_job.py:153} INFO - Started process (PID=68220) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:36:12,881] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 19:36:12,882] {logging_mixin.py:112} INFO - [2020-04-07 19:36:12,881] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:36:13,076] {logging_mixin.py:112} INFO - [2020-04-07 19:36:13,075] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:36:13,077] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:36:13,086] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.210 seconds
[2020-04-07 19:37:23,154] {scheduler_job.py:153} INFO - Started process (PID=68258) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:37:23,160] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 19:37:23,161] {logging_mixin.py:112} INFO - [2020-04-07 19:37:23,160] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:37:23,351] {logging_mixin.py:112} INFO - [2020-04-07 19:37:23,350] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:37:23,352] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:37:23,361] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.207 seconds
[2020-04-07 19:38:33,511] {scheduler_job.py:153} INFO - Started process (PID=68297) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:38:33,517] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 19:38:33,518] {logging_mixin.py:112} INFO - [2020-04-07 19:38:33,517] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:38:33,691] {logging_mixin.py:112} INFO - [2020-04-07 19:38:33,690] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:38:33,691] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:38:33,705] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.194 seconds
[2020-04-07 19:39:43,824] {scheduler_job.py:153} INFO - Started process (PID=68343) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:39:43,830] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 19:39:43,831] {logging_mixin.py:112} INFO - [2020-04-07 19:39:43,831] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:39:44,036] {logging_mixin.py:112} INFO - [2020-04-07 19:39:44,035] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:39:44,036] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:39:44,045] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.221 seconds
[2020-04-07 19:40:54,022] {scheduler_job.py:153} INFO - Started process (PID=68384) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:40:54,031] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 19:40:54,033] {logging_mixin.py:112} INFO - [2020-04-07 19:40:54,032] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:40:54,398] {logging_mixin.py:112} INFO - [2020-04-07 19:40:54,395] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:40:54,399] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:40:54,418] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.396 seconds
[2020-04-07 19:42:04,203] {scheduler_job.py:153} INFO - Started process (PID=68435) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:42:04,216] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 19:42:04,217] {logging_mixin.py:112} INFO - [2020-04-07 19:42:04,217] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:42:04,480] {logging_mixin.py:112} INFO - [2020-04-07 19:42:04,478] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:42:04,481] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:42:04,493] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.290 seconds
[2020-04-07 19:43:14,396] {scheduler_job.py:153} INFO - Started process (PID=68473) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:43:14,402] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 19:43:14,403] {logging_mixin.py:112} INFO - [2020-04-07 19:43:14,402] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:43:14,583] {logging_mixin.py:112} INFO - [2020-04-07 19:43:14,581] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:43:14,583] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:43:14,597] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.200 seconds
[2020-04-07 19:44:24,606] {scheduler_job.py:153} INFO - Started process (PID=68515) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:44:24,619] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 19:44:24,620] {logging_mixin.py:112} INFO - [2020-04-07 19:44:24,620] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:44:24,820] {logging_mixin.py:112} INFO - [2020-04-07 19:44:24,819] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:44:24,821] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:44:24,829] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.222 seconds
[2020-04-07 19:45:34,821] {scheduler_job.py:153} INFO - Started process (PID=68554) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:45:34,828] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 19:45:34,828] {logging_mixin.py:112} INFO - [2020-04-07 19:45:34,828] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:45:35,003] {logging_mixin.py:112} INFO - [2020-04-07 19:45:35,002] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:45:35,004] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:45:35,017] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.196 seconds
[2020-04-07 19:46:45,021] {scheduler_job.py:153} INFO - Started process (PID=68592) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:46:45,027] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 19:46:45,029] {logging_mixin.py:112} INFO - [2020-04-07 19:46:45,028] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:46:45,203] {logging_mixin.py:112} INFO - [2020-04-07 19:46:45,202] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:46:45,203] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:46:45,214] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.193 seconds
[2020-04-07 19:47:55,213] {scheduler_job.py:153} INFO - Started process (PID=68632) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:47:55,219] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 19:47:55,220] {logging_mixin.py:112} INFO - [2020-04-07 19:47:55,220] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:47:55,394] {logging_mixin.py:112} INFO - [2020-04-07 19:47:55,392] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:47:55,394] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:47:55,407] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.195 seconds
[2020-04-07 19:49:05,399] {scheduler_job.py:153} INFO - Started process (PID=68682) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:49:05,405] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 19:49:05,406] {logging_mixin.py:112} INFO - [2020-04-07 19:49:05,406] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:49:05,644] {logging_mixin.py:112} INFO - [2020-04-07 19:49:05,643] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:49:05,645] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:49:05,658] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.258 seconds
[2020-04-07 19:50:15,613] {scheduler_job.py:153} INFO - Started process (PID=68722) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:50:15,619] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 19:50:15,620] {logging_mixin.py:112} INFO - [2020-04-07 19:50:15,619] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:50:15,865] {logging_mixin.py:112} INFO - [2020-04-07 19:50:15,864] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:50:15,866] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:50:15,876] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.264 seconds
[2020-04-07 19:51:25,814] {scheduler_job.py:153} INFO - Started process (PID=68768) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:51:25,828] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 19:51:25,829] {logging_mixin.py:112} INFO - [2020-04-07 19:51:25,828] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:51:26,198] {logging_mixin.py:112} INFO - [2020-04-07 19:51:26,197] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:51:26,199] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:51:26,208] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.393 seconds
[2020-04-07 19:52:36,025] {scheduler_job.py:153} INFO - Started process (PID=68814) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:52:36,034] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 19:52:36,035] {logging_mixin.py:112} INFO - [2020-04-07 19:52:36,034] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:52:36,415] {logging_mixin.py:112} INFO - [2020-04-07 19:52:36,413] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:52:36,415] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:52:36,425] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.399 seconds
[2020-04-07 19:53:46,248] {scheduler_job.py:153} INFO - Started process (PID=68862) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:53:46,254] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 19:53:46,255] {logging_mixin.py:112} INFO - [2020-04-07 19:53:46,255] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:53:46,673] {logging_mixin.py:112} INFO - [2020-04-07 19:53:46,672] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:53:46,674] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:53:46,683] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.435 seconds
[2020-04-07 19:54:56,473] {scheduler_job.py:153} INFO - Started process (PID=68929) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:54:56,490] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 19:54:56,491] {logging_mixin.py:112} INFO - [2020-04-07 19:54:56,491] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:54:56,852] {logging_mixin.py:112} INFO - [2020-04-07 19:54:56,850] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:54:56,853] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:54:56,871] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.398 seconds
[2020-04-07 19:56:06,653] {scheduler_job.py:153} INFO - Started process (PID=68968) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:56:06,660] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 19:56:06,662] {logging_mixin.py:112} INFO - [2020-04-07 19:56:06,661] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:56:06,931] {logging_mixin.py:112} INFO - [2020-04-07 19:56:06,862] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:56:06,931] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:56:06,943] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.290 seconds
[2020-04-07 19:57:16,866] {scheduler_job.py:153} INFO - Started process (PID=69014) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:57:16,873] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 19:57:16,874] {logging_mixin.py:112} INFO - [2020-04-07 19:57:16,874] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:57:17,197] {logging_mixin.py:112} INFO - [2020-04-07 19:57:17,196] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:57:17,197] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:57:17,204] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.338 seconds
[2020-04-07 19:58:27,083] {scheduler_job.py:153} INFO - Started process (PID=69053) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:58:27,090] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 19:58:27,091] {logging_mixin.py:112} INFO - [2020-04-07 19:58:27,091] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:58:27,392] {logging_mixin.py:112} INFO - [2020-04-07 19:58:27,391] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:58:27,392] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:58:27,400] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.317 seconds
[2020-04-07 19:59:37,256] {scheduler_job.py:153} INFO - Started process (PID=69097) to work on /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:59:37,269] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py for tasks to queue
[2020-04-07 19:59:37,270] {logging_mixin.py:112} INFO - [2020-04-07 19:59:37,270] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:59:37,704] {logging_mixin.py:112} INFO - [2020-04-07 19:59:37,703] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py", line 49, in <module>
    t2 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:59:37,705] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py
[2020-04-07 19:59:37,711] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/kaggle_dag copy.py took 0.455 seconds
