[2020-04-07 08:30:51,107] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: atp_data05.connect_pst 2020-04-06T00:00:00+00:00 [queued]>
[2020-04-07 08:30:51,113] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: atp_data05.connect_pst 2020-04-06T00:00:00+00:00 [queued]>
[2020-04-07 08:30:51,113] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2020-04-07 08:30:51,113] {taskinstance.py:867} INFO - Starting attempt 1 of 2
[2020-04-07 08:30:51,113] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2020-04-07 08:30:51,118] {taskinstance.py:887} INFO - Executing <Task(PythonOperator): connect_pst> on 2020-04-06T00:00:00+00:00
[2020-04-07 08:30:51,120] {standard_task_runner.py:53} INFO - Started process 50391 to run task
[2020-04-07 08:30:51,163] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: atp_data05.connect_pst 2020-04-06T00:00:00+00:00 [running]> 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2020-04-07 08:30:51,414] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-04-07 08:30:51,420] {taskinstance.py:1048} INFO - Marking task as SUCCESS.dag_id=atp_data05, task_id=connect_pst, execution_date=20200406T000000, start_date=20200407T123051, end_date=20200407T123051
[2020-04-07 08:31:01,104] {logging_mixin.py:112} INFO - [2020-04-07 08:31:01,103] {local_task_job.py:103} INFO - Task exited with return code 0
